/*CREATE TYPE masteryEnum AS ENUM ('Bad', 'Average', 'Good', 'Master');
*/
create table revision (
                      id bigint not null generated by default as identity ,
                      quarter_number numeric not null,
                      mastery varchar(50),
                      time_updated date,
                      urgency boolean default false,
                      primary key (id)
);