/*CREATE TYPE masteryEnum AS ENUM ('Bad', 'Average', 'Good', 'Master');
*/
create table revision
(
    id                                      bigint      not null generated by default as identity,
    quarter_number                          numeric     not null,
    mastery                                 varchar(50),
    time_updated                            timestamp,
    urgency                                 boolean default false,
    ref_username                            varchar(50) not null,
    time_added                              timestamp,
    manually_set_urgency_flag               boolean default false,
    date_of_setting_the_manual_urgency_flag timestamp,
    primary key (id)
);

create table log_Revised
(
    id                             bigint      not null generated by default as identity,
    quarter_number                 numeric     not null,
    mastery                        varchar(50),
    date_revised                   timestamp,
    time_needed_to_finish_revision time,
    ref_username                   varchar(50) not null,

    primary key (id)
);

create table users
(
    id           bigint             not null generated by default as identity,
    user_name    varchar(50) unique not null,
    time_created timestamp,
    last_login   timestamp,
    primary key (id)
);


--------Foreign Keys Reference
alter table if exists revision
    add constraint FK_REVISION_REF_USER foreign key (ref_username) references users (user_name);
alter table if exists log_Revised
    add constraint FK_LOG_REVISED_REF_USER foreign key (ref_username) references users (user_name);

--------Unique Keys Constraints
alter table if exists users
    add constraint UK_USER_REF unique (user_name);


--Not sure if I reference them
--alter table if exists revision add constraint UK_REVISION_REF_USER unique (ref_username);
--alter table if exists log_Revised add constraint UK_LOG_REVISED_REF_USER unique (ref_username);