
create table log_Revised (
                             id bigint not null generated by default as identity ,
                             quarter_number numeric not null,
                             mastery varchar(50),
                             time_revised date,
                             primary key (id)
)
